apiVersion: apps/v1
kind: Deployment
metadata:
  name: vivance-auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vivance-auth-api
  template:
    metadata:
      labels:
        app: vivance-auth-api
    spec:
      containers:
      - name: vivance-auth-api
        image: vivance/auth-gateway:develop
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
        env:
          - name: SPRING_CONFIG_LOCATION
            value: "file:/config/auth-api.yaml"
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: java-mysql-secret
                key: JWT_SECRET
        volumeMounts:
          - name: config-volume
            mountPath: /config/auth-api.yaml
            subPath: auth-api.yaml
            readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: auth-api-config
---
apiVersion: v1
kind: Service
metadata:
  name: vivance-auth-api-service
spec:
  type: NodePort
  selector:
    app: vivance-auth-api
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30084
