spring.datasource.url=jdbc:mysql://localhost:3306/vivance_java?useSSL=false&serverTimezone=UTC
spring.datasource.username=java_user
spring.datasource.password=
spring.jpa.show-sql=true

# Add more client IDs as comma-separated values when Android/iOS are ready
auth.google.client-ids=686128296668-kj7ptbgutavu99kefvk1fgiq8pti9j6b.apps.googleusercontent.com

auth.apple.client-id=com.vivance.app
